// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MathDao is an autogenerated mock type for the MathDao type
type MathDao struct {
	mock.Mock
}
