// Code generated by mocker. DO NOT EDIT.
// github.com/travisjeffery/mocker
// Source: math_dao.go

package mock

// MockMathDao is a mock of MathDao interface
type MockMathDao struct {
	calls struct {
	}
}

// Reset resets the calls made to the mocked methods.
func (m *MockMathDao) Reset() {
}
